### ISSUE TITLE
Hubot refuses to load module

### ISSUE THREAD

**Issue by indiggio** [willgarcia/hubot-openstack#1] opened 2015-08-31 20:23 UTC
I've added the hubot-openstack as normal, but no matter what I do, I can't get Hubot to load the script??

I've added some additional debug statements to the Hubot code in the hopes of figuring this out, but it seems to fall into the "require(pkg)(@)" statement in robot.coffee, but then it gets lost.
Here's the output:

[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: hubot-diagnostics,hubot-help,hubot-google-translate,hubot-pugme,hubot-maps,hubot-redis-brain,hubot-rules,hubot-shipit,hubot-daily-comic,hubot-openstack
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-diagnostics
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-help
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-google-translate
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-pugme
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-maps
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-redis-brain
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-rules
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-shipit
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-daily-comic
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Requiring pkg:hubot-openstack
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadExternalScripts: Done
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-diagnostics/src/diagnostics.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-diagnostics/src/diagnostics.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-help/src/help.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-help/src/help.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-google-translate/src/google-translate.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-google-translate/src/google-translate.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-pugme/src/pugme.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-pugme/src/pugme.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-maps/src/maps.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-maps/src/maps.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-redis-brain/src/redis-brain.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-redis-brain/src/redis-brain.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-rules/src/rules.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-rules/src/rules.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-shipit/src/shipit.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-shipit/src/shipit.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-daily-comic/scripts/hubot-daily-comic.coffee
[Mon Aug 31 2015 15:14:44 GMT-0500 (CDT)] DEBUG Parsing help for /home/ubuntu/alfred/node_modules/hubot-daily-comic/scripts/hubot-daily-comic.coffee
Joined Hubot

As can be seen, hubot-openstack is in the list if packages and the "require(pkg)(@)" statement is called with it as a parameter, but eventually no "Parsing help..." line is output for hubut-openstack?

Also, when I try to send the bot a openstack-compute command, all I get is:
DEBUG No listeners executed; falling back to catch-all
which indicates that Hubot is not calling the openstack-compute to parse the request?

Thanks!

**Comment by willgarcia** [comment] 2015-09-01 20:42
@indiggio - thanks for the bug report!

Give the current fix a try: if everything is ok (seems ok on my bot), I'll merge / release a new version.

**Comment by indiggio** [comment] 2015-09-01 20:52
No problem!

I entered the fix and now I see my debug line indicating it's being loaded.
[Tue Sep 01 2015 15:46:30 GMT-0500 (CDT)] DEBUG loadFile: /home/ubuntu/alfred/node_modules/hubot-openstack/scripts/undefined

I don't know what that undefined is, but it doesn't look good to me...
Note that there is one file, openstack.js, in the hubot-openstack/scripts directory.

Also, when I try to send the bot a command (@bot openstack-compute flavors) I get:
[Tue Sep 01 2015 15:49:08 GMT-0500 (CDT)] DEBUG No listeners executed; falling back to catch-all

Is there a way to help debug that?  Sorry I'm new to all this.

Thanks!

**Comment by willgarcia** [comment] 2015-09-02 06:51
What's your hubot version in the `package.json` (so I can try to reproduce) ? mine's `"hubot": "~2.11"`

**Comment by indiggio** [comment] 2015-09-02 09:17
Mine's `"hubot": "~2.16.0"`

**Comment by ronakbanka** [comment] 2015-10-24 03:09
@willgarcia Changing to scripts works for me. hubot version : 2.16

**Comment by willgarcia** [comment] 2015-10-25 18:19
Fixed by #3.

**Closed as completed by willgarcia** 2015-10-25 18:19 UTC
